export const industryAiSourceUrl = "https://mp.weixin.qq.com/s/tvnb-nhZxqPIkE_X-CpbvA?mpshare=1&scene=1&srcid=0810IgRzrvjRDiYs2sTP3phI&sharer_shareinfo=25a5aa97983a24bc5b5cf5fbda2b4460&sharer_shareinfo_first=c4e0bf30baa5b6049d34a8a3036a90cd&color_scheme=light#rd";

export const industryAiCategories = [
  { id: "all", label: "全部能力", short: "全景", color: "blue" },
  { id: "design", label: "设计 / BIM", short: "设计", color: "purple" },
  { id: "build", label: "施工 / 安全", short: "建造", color: "orange" },
  { id: "cost", label: "造价 / 合同", short: "成本", color: "green" },
  { id: "knowledge", label: "知识 / Copilot", short: "知识", color: "violet" },
  { id: "ops", label: "运维 / 管理", short: "运维", color: "teal" },
  { id: "physical", label: "物理 AI / 仿真", short: "仿真", color: "red" },
];

// Article-level scope. The product cards below are intentionally curated representatives,
// while the article itself covers a broader case and scenario set.
export const industryAiArticleMeta = {
  totalCases: 90,
  totalScenarios: 25,
  sourceRegions: 4,
  sampleLabel: "已展开代表性样本",
};

export const industryAiStages = [
  { id: "all", label: "全部工程阶段" },
  { id: "design", label: "设计与审图" },
  { id: "build", label: "施工与交付" },
  { id: "manage", label: "经营与成本" },
  { id: "operate", label: "运维与决策" },
];

export const industryAiProducts = [
  {
    id: "archigpt",
    name: "赢技 ArchiGPT",
    category: "design",
    stage: "design",
    type: "设计软件",
    company: "赢技科技",
    signal: "CAD → BIM",
    summary: "从 CAD 图纸提取数据、生成 BIM 模型，并辅助管线碰撞处理，打通后续算量、图审与运维数据链。",
    capability: ["图纸理解", "BIM 生成", "碰撞检查"],
    maturity: "场景验证",
    attention: "把 AI 设计能力嵌入工程数据链，而不是停留在效果图生成。",
    sourceLabel: "公开案例索引",
    sourceUrl: "https://2048ai.net/69bcdf780a2f6a37c598cc95.html",
  },
  {
    id: "xinzhu-ai",
    name: "信筑 AI 平台",
    category: "design",
    stage: "design",
    type: "设计院平台",
    company: "中信建筑设计研究总院",
    signal: "生成 + 规范",
    summary: "围绕灵感生成、模型训练和规范检索，支持设计师快速探索方案并获得合规性辅助支撑。",
    capability: ["方案生成", "风格模型", "规范检索"],
    maturity: "规模应用",
    attention: "细分风格模型与行业规范库结合，是设计院形成差异化壁垒的典型路径。",
    sourceLabel: "公开案例索引",
    sourceUrl: "https://2048ai.net/69bcdf780a2f6a37c598cc95.html",
  },
  {
    id: "archineur",
    name: "ArchiNeur",
    category: "design",
    stage: "design",
    type: "创意终端",
    company: "上海建筑设计研究院",
    signal: "草图 → 方案",
    summary: "基于提示词与参考草图生成建筑、立面和景观创意，并支持实时优化与规范校验。",
    capability: ["多模态生成", "方案迭代", "规范校验"],
    maturity: "场景验证",
    attention: "生成结果进入工程流程的关键，不是图像质量，而是可迭代、可校验、可落地。",
    sourceLabel: "公开案例索引",
    sourceUrl: "https://2048ai.net/69bcdf780a2f6a37c598cc95.html",
  },
  {
    id: "pinming-drawing",
    name: "品茗 AI 图模管理",
    category: "design",
    stage: "build",
    type: "图模管理",
    company: "品茗科技",
    signal: "图纸版本",
    summary: "面向施工图纸与模型的智能管控，降低现场用错图、找图难和版本协同成本。",
    capability: ["图纸识别", "版本比对", "施工协同"],
    maturity: "规模应用",
    attention: "图纸版本一致性是施工现场最容易量化 ROI 的 AI 切入口之一。",
    sourceLabel: "厂商公开报道",
    sourceUrl: "https://www.pinming.cn/news_cont_6179.html",
  },
  {
    id: "jzleap",
    name: "JZLEAP 工程 AI 引擎",
    category: "design",
    stage: "design",
    type: "行业引擎",
    company: "JZLEAP",
    signal: "工程专用 AI",
    summary: "面向建筑施工行业，把图纸解析、造价审核、进度跟踪等通用 AI 能力落到具体工程环节。",
    capability: ["图纸解析", "造价审核", "进度跟踪"],
    maturity: "产品化",
    attention: "从模型能力层下沉到任务引擎层，才有机会承接工程业务闭环。",
    sourceLabel: "厂商官网",
    sourceUrl: "https://jzleap.com/",
  },
  {
    id: "bim-review",
    name: "AI + BIM 施工图智能审查",
    category: "design",
    stage: "design",
    type: "图审系统",
    company: "湖北住建系统 / 华中科技大学",
    signal: "规范匹配",
    summary: "将施工图审查条文知识库与 BIM 数据结合，实现规范条款匹配、问题构件定位和模型分析。",
    capability: ["条文检索", "智能审图", "构件定位"],
    maturity: "规模应用",
    attention: "知识库不再只是问答入口，而是直接参与审查规则执行。",
    sourceLabel: "公开案例索引",
    sourceUrl: "https://2048ai.net/69bcdf780a2f6a37c598cc95.html",
  },
  {
    id: "tianchan",
    name: "天蝉施工机器人系统",
    category: "build",
    stage: "build",
    type: "施工机器人",
    company: "中建八局等",
    signal: "AI + 机器人",
    summary: "以 AI 智巡和无人施工装备协同为核心，覆盖浇筑、构件安装和现场巡检等工序。",
    capability: ["现场感知", "机器人协同", "工序执行"],
    maturity: "示范应用",
    attention: "当 AI 从识别进入现场执行，产品形态会从软件工具升级为软硬一体系统。",
    sourceLabel: "公开案例索引",
    sourceUrl: "https://2048ai.net/69bcdf780a2f6a37c598cc95.html",
  },
  {
    id: "site-hazards",
    name: "施工现场多隐患智能判定",
    category: "build",
    stage: "build",
    type: "安全视觉",
    company: "重庆赛迪工程咨询",
    signal: "一图多检",
    summary: "基于海量安全隐患图像，对高处作业、临电、吊篮、起重机械等风险进行同步识别与预警。",
    capability: ["视觉识别", "风险预警", "规范匹配"],
    maturity: "场景验证",
    attention: "从单一告警升级到多隐患并行判定，模型价值更贴近现场检查工作量。",
    sourceLabel: "公开案例索引",
    sourceUrl: "https://2048ai.net/69bcdf780a2f6a37c598cc95.html",
  },
  {
    id: "site-supervision",
    name: "工地智慧监管体系",
    category: "build",
    stage: "build",
    type: "工地监管",
    company: "湖北住建系统 / 华中科技大学",
    signal: "14 类隐患",
    summary: "接入工地摄像头，持续监测反光衣、塔吊等安全隐患并推送事件，形成监管侧智能巡查能力。",
    capability: ["视频分析", "事件推送", "监管闭环"],
    maturity: "规模应用",
    attention: "公共监管平台一旦积累事件与处置数据，能反向训练区域级安全模型。",
    sourceLabel: "公开案例索引",
    sourceUrl: "https://2048ai.net/69bcdf780a2f6a37c598cc95.html",
  },
  {
    id: "deep-foundation",
    name: "深基坑安全风险管控助手",
    category: "build",
    stage: "build",
    type: "风险管控",
    company: "上海勘察设计研究院",
    signal: "知识图谱 + 大模型",
    summary: "融合监测数据、知识图谱与大模型，识别沉降、位移等风险，给出处置建议并关联历史案例。",
    capability: ["时序监测", "风险研判", "方案推荐"],
    maturity: "场景验证",
    attention: "工程 AI 的高价值形态是“识别 + 解释 + 建议”，而不是只给出一个风险分数。",
    sourceLabel: "公开案例索引",
    sourceUrl: "https://2048ai.net/69bcdf780a2f6a37c598cc95.html",
  },
  {
    id: "safety-copilot",
    name: "智慧工地全域安全智控大模型",
    category: "build",
    stage: "build",
    type: "安全大模型",
    company: "中城交（上海）科技",
    signal: "安全闭环",
    summary: "覆盖人员、设备、环境和工序，通过视觉识别与数据分析实现隐患识别、预警、处置闭环。",
    capability: ["全域感知", "隐患闭环", "安全决策"],
    maturity: "示范应用",
    attention: "安全场景的竞争核心正在从单点算法转向事件流、处置流和责任流的整合。",
    sourceLabel: "公开案例索引",
    sourceUrl: "https://2048ai.net/69bcdf780a2f6a37c598cc95.html",
  },
  {
    id: "cost-assistant",
    name: "造价 AI 智能助手",
    category: "cost",
    stage: "manage",
    type: "造价助手",
    company: "湖北建设工程标准定额管理总站等",
    signal: "清单计价",
    summary: "围绕指标计算、信息价查询和房建项目分析，辅助成本预测、投标决策和清单计价。",
    capability: ["指标分析", "信息价查询", "计价生成"],
    maturity: "规模应用",
    attention: "造价场景的数据结构化程度高，适合优先做可审计、可回溯的 Agent。",
    sourceLabel: "公开案例索引",
    sourceUrl: "https://2048ai.net/69bcdf780a2f6a37c598cc95.html",
  },
  {
    id: "newgrand-cost",
    name: "新中大成本测算智能体",
    category: "cost",
    stage: "manage",
    type: "成本智能体",
    company: "新中大",
    signal: "材料归一",
    summary: "针对材料多名称、价格匹配和历史数据复用，提供工程成本测算与询价辅助。",
    capability: ["材料识别", "价格分析", "成本测算"],
    maturity: "产品化",
    attention: "材料主数据治理是成本 AI 的底座，模型效果最终取决于企业历史数据是否可复用。",
    sourceLabel: "工程 AI 产品市场",
    sourceUrl: "https://www.gch168.com/",
  },
  {
    id: "contract-agent",
    name: "合同审核智能体",
    category: "cost",
    stage: "manage",
    type: "合同风控",
    company: "工程 AI 产品市场收录",
    signal: "合规底线",
    summary: "围绕招投标与合同条款进行行业标准匹配和风险提示，承担企业风控第一道检查。",
    capability: ["条款抽取", "风险识别", "合规校验"],
    maturity: "产品化",
    attention: "合同 Agent 适合与企业审批流、模板库和风险责任链共同落地。",
    sourceLabel: "工程 AI 产品市场",
    sourceUrl: "https://www.gch168.com/",
  },
  {
    id: "cad-kb",
    name: "CAD-KB",
    category: "knowledge",
    stage: "operate",
    type: "工程知识大脑",
    company: "北京图晟科技",
    signal: "DWG + RAG",
    summary: "以 DWG/PDF 图纸全模态解析为入口，构建工程知识库，并延伸到问答、方案编制和业务系统集成。",
    capability: ["图纸解析", "知识检索", "工程智能体"],
    maturity: "产品化",
    attention: "工程知识库的差异化不在文档数量，而在图纸结构化和业务动作的连接能力。",
    sourceLabel: "厂商官网",
    sourceUrl: "https://www.tushengai.com/",
  },
  {
    id: "liangce",
    name: "良策金宝",
    category: "knowledge",
    stage: "operate",
    type: "工程师助手",
    company: "金口良策",
    signal: "规范 + 计算",
    summary: "面向电力工程师，覆盖规范检索、工程计算、项目书、可研报告与 CAD 图纸等日常工作。",
    capability: ["规范搜索", "工程计算", "文档生成"],
    maturity: "产品化",
    attention: "垂直 Copilot 通过“规范、计算、文档、图纸”组合，形成比通用问答更强的任务入口。",
    sourceLabel: "App Store 公开介绍",
    sourceUrl: "https://apps.apple.com/cn/app/%E8%89%AF%E7%AD%96%E9%87%91%E5%AE%9D-%E5%B7%A5%E7%A8%8B%E4%BA%BAai%E6%95%88%E7%8E%87%E7%A5%9E%E5%99%A8/id6746497694?l=en-GB&platform=mac",
  },
  {
    id: "gongyi-cloud",
    name: "工一云",
    category: "knowledge",
    stage: "operate",
    type: "工程智能体平台",
    company: "工一云",
    signal: "业务 + AI",
    summary: "把云办公、AI 智能、工程业务与工程教育放在同一平台，强调工程知识与业务系统的融合。",
    capability: ["智能办公", "业务分析", "工程教育"],
    maturity: "产品化",
    attention: "行业平台的长期价值，在于让 AI 直接调用项目、协同与监管数据。",
    sourceLabel: "厂商官网",
    sourceUrl: "https://cec.cc/",
  },
  {
    id: "red-circle-ai",
    name: "红圈 AI",
    category: "ops",
    stage: "manage",
    type: "工程经营管理",
    company: "和创科技",
    signal: "项目经营",
    summary: "在工程项目管理、CRM 与销售服务系统上叠加 AI，连接线索、招投标、项目与回款等经营链路。",
    capability: ["项目管理", "经营分析", "风险提示"],
    maturity: "规模应用",
    attention: "AI 进入工程企业后，经营数据和项目数据会成为比单点效率更大的价值池。",
    sourceLabel: "厂商官网",
    sourceUrl: "https://www.hecom.cn/",
  },
  {
    id: "utility-corridor",
    name: "综合管廊主动防控",
    category: "ops",
    stage: "operate",
    type: "基础设施运维",
    company: "中冶赛迪信息技术",
    signal: "预测性运维",
    summary: "结合视频分析、时序预测和自然语言指令，实现管廊入侵、积水、火灾与环境风险的主动防控。",
    capability: ["视频分析", "趋势预测", "自然语言运维"],
    maturity: "示范应用",
    attention: "运维 AI 从“发现异常”走向“提前研判 + 调取信息 + 处置建议”。",
    sourceLabel: "公开案例索引",
    sourceUrl: "https://2048ai.net/69bcdf780a2f6a37c598cc95.html",
  },
  {
    id: "sorun-physical-ai",
    name: "索辰物理 AI",
    category: "physical",
    stage: "design",
    type: "工程仿真",
    company: "索辰信息",
    signal: "仿真 + 物理约束",
    summary: "将高保真渲染、物理约束建模、实时数据驱动优化等能力用于复杂工程研发与验证。",
    capability: ["多物理仿真", "数据优化", "虚拟验证"],
    maturity: "产品化",
    attention: "物理 AI 为工程软件提供另一条增长曲线：从生成内容转向预测物理结果。",
    sourceLabel: "公司年报公开披露",
    sourceUrl: "https://app.cnstock.com/zzb/zgzqb/html/2026-04/28/nw.D110000zgzqb_20260428_1-B655.htm",
  },
];

export const industryAiHighlights = [
  { index: "01", title: "图纸成为 AI 的新入口", text: "CAD / BIM / PDF 不再只是附件，而是被解析为可检索、可计算、可调用的工程数据资产。", tag: "数据底座" },
  { index: "02", title: "从单点识别走向闭环执行", text: "安全、审图、造价和运维产品都在把识别结果接入预警、审批、整改或写回流程。", tag: "工作流" },
  { index: "03", title: "规范知识开始参与决策", text: "规范库不只是问答材料，正在变成审查条文、合同底线和风险建议的可执行规则。", tag: "知识工程" },
  { index: "04", title: "软硬一体的工程 AI 出现", text: "施工机器人、无人机、摄像头与数字孪生让 AI 进入现场，带来更高的交付门槛与数据壁垒。", tag: "具身现场" },
  { index: "05", title: "垂直 Copilot 进入工作台", text: "工程师助手把规范、计算、文档、图纸和业务系统聚合到一个任务入口，争夺日常工作流。", tag: "人机协同" },
];

export const industryAiPlaybook = [
  { phase: "现在", title: "先做可审计的高频任务", text: "图纸检索、规范匹配、版本比对、材料归一、合同初审。" },
  { phase: "下一步", title: "把结果接入业务流", text: "将识别、建议与审批、整改、写回和责任链连接起来。" },
  { phase: "长期", title: "沉淀企业工程数据资产", text: "围绕图纸、项目、规范、事件与决策记录形成专属知识和模型壁垒。" },
];

